"""create scans table

Revision ID: 2238192dae9f
Revises: 
Create Date: 2026-01-19 12:24:10.764715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2238192dae9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'overall_score')
    op.drop_column('scans', 'summary')
    op.drop_column('scans', 'vulnerabilities_count')
    op.drop_column('scans', 'scanned_at')
    op.drop_column('scans', 'severity_breakdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('severity_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('scans', sa.Column('scanned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('vulnerabilities_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scans', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('scans', sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
