"""add vulnerabilities_count to scans

Revision ID: 48ef6f0801a4
Revises: 2238192dae9f
Create Date: 2026-01-19 15:22:56.657198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ef6f0801a4'
down_revision: Union[str, Sequence[str], None] = '2238192dae9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column with default value
    op.add_column(
        'scans',
        sa.Column('vulnerabilities_count', sa.Integer(), server_default='0', nullable=False)
    )

    # 2. Remove server default (optional but clean)
    op.alter_column('scans', 'vulnerabilities_count', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'vulnerabilities_count')
    # ### end Alembic commands ###
