"""add overall_score and summary to scans

Revision ID: dfc2cc892ab9
Revises: b2407ca583f0
Create Date: 2026-01-19 15:35:36.644212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc2cc892ab9'
down_revision: Union[str, Sequence[str], None] = 'b2407ca583f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'scans',
        sa.Column('overall_score', sa.Float(), server_default='0', nullable=False)
    )
    op.add_column(
        'scans',
        sa.Column('summary', sa.Text(), server_default='', nullable=False)
    )

    op.alter_column('scans', 'overall_score', server_default=None)
    op.alter_column('scans', 'summary', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'summary')
    op.drop_column('scans', 'overall_score')
    # ### end Alembic commands ###
