"""Add API keys table

Revision ID: f4476469e0d7
Revises:
Create Date: 2026-01-28 09:14:04.577739

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f4476469e0d7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
